name: Test

on:
  push:
    branches:
      - master
      - v*
      - dev-*
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Test
        run: go test -v -timeout 1h ./...
